apiVersion: v1
kind: Service
metadata:
    name: cluster_ip
spec:
    type: ClusterIP
    selector:
        app: label_pod_1           # servico aponta para o pod 1 - usa label do pod_1
    ports: 
      - port: 80                   # escuta pela porta 80 
      targetPort : 9000            # envia para a porta 9000 do pod_1