apiVersion: v1
kind: Pod
metadata:
    name: pod_db
    labels:
        app: label_pod_db
spec:
    containers:
        - name: db-container
        image: path/mysql-db:1
        ports:
          - containerPort: 3306
    env: # variaveis do mysql
      - name: "MYSQL_ROOT_PASSWORD"
        value: "q1w2e3r4"
      - name: "MYSQL_DATABASE"
        value: "db"
      - name: "MYSQL_PASSWORD"
        value : "q1w2e3r4"