apiVersion: v1
kind: Service
metadata:
    name: load_balancer
spec:
    type: LoadBalancer             # é um node port - consequentemente eh tbm um cluster ip
    ports: 
      - port: 80                   # escuta pela porta 80 
      targetPort : 80              # envia para a porta 80 do pod_1
      nodePort: 3000               # bind da porta
    selector :
      app: label_pod_1             # balanceia pod_1 