apiVersion: v1
kind: Pod
metadata:
    name: pod_1
    labels:
        app: label_pod_1
spec:
    containers:
        - name: nginx-container
        image: nginx-stable
        ports:
          - containerPort: 80