apiVersion: v1
kind: Pod
metadata:
    name: pod_db
    labels:
        app: label_pod_db
spec:
    containers:
      - name: db-container
        image: path/mysql-db:1
        ports:
          - containerPort: 3306
        envFrom:
          -configMapRef:
            name: database-configmap